alias ls='ls --color=auto'
alias l.='ls -d .* --color=auto'
alias ll='ls -l --color=auto'
alias la='ls -lA --color=auto'
alias D='cd /home/$USER/Documents/dev'
alias L='cd /home/$USER/Documents/library'
alias N='cd /home/$USER/Documents/notes'
alias config='/usr/bin/git --git-dir=/home/$USER/.dotfiles/ --work-tree=/home/$USER'
alias vim='nvim'
